# WhiteBeet SLAC - Basic Configuration (Python Module)
# Minimal configuration for testing WhiteBeet SLAC Python module

active_modules:
  whitebeet_slac:
    module: WhiteBeetSlac
    config_implementation:
      main:
        device: eth0
        whitebeet_mac: "c4:93:00:34:a4:e4"
        slac_timeout_ms: 50000
        publish_mac_on_match_cnf: true

settings: {}
